-- MySQL Script generated by MySQL Workbench
-- Wed May 13 10:57:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WorkForce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WorkForce` ;

-- -----------------------------------------------------
-- Schema WorkForce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WorkForce` ;
USE `WorkForce` ;

-- -----------------------------------------------------
-- Table `WorkForce`.`Cityes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Cityes` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Cityes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Status` VARCHAR(20) NULL DEFAULT 'Active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Users` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `CityId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Users_City_idx` (`CityId` ASC) VISIBLE,
  CONSTRAINT `fk_Users_City`
    FOREIGN KEY (`CityId`)
    REFERENCES `WorkForce`.`Cityes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`TaskCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`TaskCategory` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`TaskCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(20) NULL DEFAULT 'Active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Descr` VARCHAR(200) NOT NULL,
  `clientId` INT NOT NULL,
  `workerId` INT NULL,
  `taskCategoryId` INT NOT NULL,
  `CityId` INT NULL,
  `Lat` FLOAT NULL,
  `Lng` FLOAT NULL,
  `Budget` DECIMAL(15,2) NULL,
  `Status` VARCHAR(20) NULL,
  `DeadLine` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTasks_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Tsks_Users_Client_idx` (`clientId` ASC) VISIBLE,
  INDEX `fk_Tasks_Users_Worker_idx` (`workerId` ASC) INVISIBLE,
  INDEX `fk_Tasks_TaskCategoryId` (`taskCategoryId` ASC) VISIBLE,
  INDEX `fk_Tasks_CityId_idx` (`CityId` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_Users_Client`
    FOREIGN KEY (`clientId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_Users_Worker`
    FOREIGN KEY (`workerId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_TaskCategoryId`
    FOREIGN KEY (`taskCategoryId`)
    REFERENCES `WorkForce`.`TaskCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_CityId`
    FOREIGN KEY (`CityId`)
    REFERENCES `WorkForce`.`Cityes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`UserSkills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`UserSkills` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`UserSkills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `isActive` TINYINT NULL DEFAULT 0,
  `categoryId` INT NOT NULL,
  `Status` VARCHAR(20) NULL DEFAULT 'Active',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) INVISIBLE,
  INDEX `userId` (`userId` ASC) INVISIBLE,
  INDEX `fk_UserSkills_TaskCategory1_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_UserSkills_TaskCategory`
    FOREIGN KEY (`categoryId`)
    REFERENCES `WorkForce`.`TaskCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserSkills_Users`
    FOREIGN KEY (`userId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Messages` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `AuthorId` INT NOT NULL,
  `CorespodentId` INT NOT NULL,
  `Message` VARCHAR(200) NOT NULL,
  `MessageText` BLOB NULL,
  `TaskId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Messages_AuthorId_idx` (`AuthorId` ASC) VISIBLE,
  INDEX `fk_Messages_CorrId_idx` (`CorespodentId` ASC) VISIBLE,
  INDEX `fk_Messages_Tasks_idx` (`TaskId` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_AuthorId`
    FOREIGN KEY (`AuthorId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_CorrId`
    FOREIGN KEY (`CorespodentId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Tasks`
    FOREIGN KEY (`TaskId`)
    REFERENCES `WorkForce`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`Files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Files` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `File` BLOB NULL,
  `TaskId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Files_Tasks_idx` (`TaskId` ASC) VISIBLE,
  CONSTRAINT `fk_Files_Tasks`
    FOREIGN KEY (`TaskId`)
    REFERENCES `WorkForce`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`Responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`Responses` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`Responses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TaskId` INT NOT NULL,
  `WorkerId` INT NOT NULL,
  `Budget` DECIMAL(15,2) NULL,
  `ResponseCategory` INT NULL,
  `Comment` VARCHAR(200) NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Responses_Tasks_idx` (`TaskId` ASC) VISIBLE,
  INDEX `fk_Responses_Workers_idx` (`WorkerId` ASC) VISIBLE,
  UNIQUE INDEX `UniqueResponse` (`TaskId` ASC, `WorkerId` ASC) VISIBLE,
  CONSTRAINT `fk_Responses_Tasks`
    FOREIGN KEY (`TaskId`)
    REFERENCES `WorkForce`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responses_Workers`
    FOREIGN KEY (`WorkerId`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`ProcessCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`ProcessCategory` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`ProcessCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`UserProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`UserProfile` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`UserProfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Photo` BLOB NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_UserProfile_User`
    FOREIGN KEY (`id`)
    REFERENCES `WorkForce`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WorkForce`.`TaskProcess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WorkForce`.`TaskProcess` ;

CREATE TABLE IF NOT EXISTS `WorkForce`.`TaskProcess` (
  `id` INT NOT NULL,
  `ProcessCategory` INT NULL,
  `Date` DATETIME NULL,
  `TaskId` INT NULL,
  `Comment` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TaskProcess_idx` (`TaskId` ASC) VISIBLE,
  INDEX `fk_TaskProcess_ProcessCategory_idx` (`ProcessCategory` ASC) VISIBLE,
  CONSTRAINT `fk_TaskProcess_Tasks`
    FOREIGN KEY (`TaskId`)
    REFERENCES `WorkForce`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskProcess_ProcessCategory`
    FOREIGN KEY (`ProcessCategory`)
    REFERENCES `WorkForce`.`ProcessCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
